### PR TITLE
Various Updates

### LINKED ISSUE #1: Python distribution
The installer pulls a complete python distribution (Miniconda 3)  from 

http://navigator.oceansdata.ca/cdn/miniconda-distro.tar.gz

I assume this a custom distribution. **Where in the repo is the code that builds this distribution?**  

Although we could prepackage it like this, it is typically more common for an installer to pull from a canonical location such as 

https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh

and then install the required packages using conda. If custom packages are needed, they can be distributed on a custom conda channel.

If nothing else, installing Python this way will miss out on any bug patches or security fixes that occur upstream.

### LINKED ISSUE #4: Upgrade to Java 11
Java 10 is no longer available as a package, it shows an error when you try and add the repository. The script should be updated to use the new version of data otherwise tomcat will not work.
Since oracle Java 11 is now pay per use (i believe) we should use open JDK.

This change should also be reflected in the tomcat server file.

(This change update doesn't appear to break anything)

### LINKED ISSUE #7: Update miniconda distro tarball
With Geoff's update there are some new dependencies introduced. Right now we have `geoff.tar.bz2` sitting in `/data/installer_data` along with `minconda-distro.tar.bz2`. We need to replace the latter with the former and re-calculate the md5 hash.

### LINKED ISSUE #9: Script broken since tar.gz has been replaced with tar.bz2
Gotta change all the file extensions to `tar.bz2` and update any `pigz` commands to use `tar -xjC -f` instead.

### PR DESCRIPTION
**Pull request by jamesprayner**
Resolves #1 
Resolves #4 
Resolves #7 
Resolves #9 

Set out to update the install script to reflect the python environment changes, ending up doing a couple things:

- Script now supports new `environment.yml` from Ocean-Data-Map-Project (#1 #7)
- Swapped `npm` for `yarn`
- Updated to java 12 (#4)
- Replaced any gz files with bz2 files (#9)
- Various spelling / command order fixes

### CODE REVIEW

File: Installer_Linux.sh [hunk 1]
```diff
@@ -114,7 +125,7 @@ fi
 sed -i "s@TDS_CONTENT@$THREDDS_CONTENT_DIR@" /opt/tomcat9/bin/setenv.sh
 
 echo
-echo "Grabbing lastest version of Navigator2Go..."
```
Comment (htmlboss) [inline Installer_Linux.sh]: hehehe
